services:
  telegram-bot:
    build: .
    container_name: telegram-caption-bot
    environment:
      - HF_HOME=/huggingface
    volumes:
      - ./hf_cache:/huggingface/hub
    restart: unless-stopped
