version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-caption-bot
    env_file:
      - .env
    environment:
      - HF_HOME=/huggingface
    volumes:
      - ./hf_cache:/huggingface/hub
    restart: unless-stopped
