version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-caption-bot
    env_file:
      - .env
    volumes:
      - ./hf_cache:/root/.cache/huggingface/hub
    restart: unless-stopped

volumes:
  hf_cache:
